//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineUps
    {
        public int Id { get; set; }
        public int QB { get; set; }
        public int RB1 { get; set; }
        public int RB2 { get; set; }
        public int WR1 { get; set; }
        public int WR2 { get; set; }
        public int WR3 { get; set; }
        public int TE { get; set; }
        public int FLEX { get; set; }
        public int DST { get; set; }
        public decimal TotalSalary { get; set; }
        public decimal ProjectedFFP { get; set; }
    }
}
