//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerLists
    {
        public int Id { get; set; }
        public int ScheduleTypeId { get; set; }
        public int Year { get; set; }
        public int Week { get; set; }
    
        public virtual Schedule_Types Schedule_Types { get; set; }
    }
}
