//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Types
    {
        public Schedule_Types()
        {
            this.PlayerLists = new HashSet<PlayerLists>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PlayerLists> PlayerLists { get; set; }
    }
}
